/* Woah that's a big array!

Let's print out each song to the console*/

let topSongs = [
  "Fortnight - Taylor Swift Featuring Post Malone",
  "Down Bad - Taylor Swift",
  "I Can Do It With A Broken Heart - Taylor Swift",
  "The Tortured Poets Department - Taylor Swift",
  "So Long, London - Taylor Swift",
  "My Boy Only Breaks His Favorite Toys - Taylor Swift",
  "But Daddy I Love Him - Taylor Swift",
  "Florida!!! - Taylor Swift Featuring Florence + The Machine",
  "Who's Afraid Of Little Old Me? - Taylor Swift",
  "Guilty As Sin? - Taylor Swift",
  "Fresh Out The Slammer - Taylor Swift",
  "loml - Taylor Swift",
  "The Alchemy - Taylor Swift",
  "The Smallest Man Who Ever Lived - Taylor Swift",
  "Beautiful Things - Benson Boone",
  "Too Sweet - Hozier",
  "Like That - Future, Metro Boomin & Kendrick Lamar",
  "Lose Control - Teddy Swims",
  "Push Ups - Drake",
  "I Can Fix Him (No Really I Can) - Taylor Swift",
  "Clara Bow - Taylor Swift",
  "Espresso - Sabrina Carpenter",
  "thanK you aIMee - Taylor Swift",
  "So High School - Taylor Swift",
  "The Black Dog - Taylor Swift",
  "imgonnagetyouback - Taylor Swift",
  "A Bar Song (Tipsy) - Shaboozey",
  "Lovin On Me - Jack Harlow",
  "Saturn - SZA",
  "The Albatross - Taylor Swift",
  "Texas Hold 'Em - Beyonce",
  "The Prophecy - Taylor Swift",
  "We Can't Be Friends (Wait For Your Love) - Ariana Grande",
  "I Hate It Here - Taylor Swift",
  "How Did It End? - Taylor Swift",
  "Chloe Or Sam Or Sophia Or Marcus - Taylor Swift",
  "Stick Season - Noah Kahan",
  "I Like The Way You Kiss Me - Artemas",
  "I Look In People's Windows - Taylor Swift",
  "I Remember Everything - Zach Bryan Featuring Kacey Musgraves",
  "Cruel Summer - Taylor Swift",
  "Greedy - Tate McRae",
  "Type Ish - Future, Metro Boomin, Travis Scott & Playboi Carti",
  "Cassandra - Taylor Swift",
  "Agora Hills - Doja Cat",
  "Peter - Taylor Swift",
  "The Bolter - Taylor Swift",
  "Wanna Be - GloRilla & Megan Thee Stallion",
  "Get It Sexyy - Sexyy Red",
  "Feather - Sabrina Carpenter",
  "The Manuscript - Taylor Swift",
  "Carnival - ¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti",
  "FTCU - Nicki Minaj",
  "Whatever She Wants - Bryson Tiller",
  "Robin - Taylor Swift",
  "End Of Beginning - Djo",
  "Redrum - 21 Savage",
  "Gata Only - FloyyMenor X Cris Mj",
  "Yeah Glo! - GloRilla",
  "Austin - Dasha",
  "Never Lose Me - Flo Milli",
  "Good Luck, Babe! - Chappell Roan",
  "Act II: Date @ 8 - 4Batz Featuring Drake",
  "Made For Me - Muni Long",
  "Where It Ends - Bailey Zimmerman",
  "Tell Ur Girlfriend - Lay Bankz",
  "FE!N - Travis Scott Featuring Playboi Carti",
  "Wild Ones - Jessie Murph & Jelly Roll",
  "Slow It Down - Benson Boone",
  "Cinderella - Future, Metro Boomin & Travis Scott",
  "Wildflowers And Wild Horses - Lainey Wilson",
  "Hell N Back - Bakar Featuring Summer Walker",
  "Back Then Right Now - Tyler Hubbard",
  "Obsessed - Olivia Rodrigo",
  "Get In With Me - BossMan Dlow",
  "Wind Up Missin' You - Tucker Wetmore",
  "Mmhmm - BigXthaPlug",
  "Illusion - Dua Lipa",
  "Bulletproof - Nate Smith",
  "Enough (Miami) - Cardi B",
  "Everybody - Nicki Minaj Featuring Lil Uzi Vert",
  "Scared To Start - Michael Marcagi",
  "La Diabla - Xavi",
  "II Most Wanted - Beyonce & Miley Cyrus",
  "Cry - Benson Boone",
  "Outskirts - Sam Hunt",
  "Tu Name - Fuerza Regida",
  "We Still Don't Trust You - Future, Metro Boomin & The Weeknd",
  "One Of The Girls - The Weeknd, Jennie & Lily Rose Depp",
  "Let's Go - Key Glock & Young Dolph",
  "23 - Chayce Beckham",
  "Tucson Too Late - Jordan Davis",
  "Halfway To Hell - Jelly Roll",
  "Praise Jah In The Moonlight - YG Marley",
  "Feel It - d4vd",
  "Us Vs. Them - $uicideBoy$",
  "Wine Into Whiskey - Tucker Wetmore",
  "Spin You Around (1/24) - Morgan Wallen",
  "Soak City - 310babii",
  "Selfish - Justin Timberlake"
];

